### ISSUE TITLE
Build deployment pipeline

### ISSUE THREAD

**Issue by scytherswings** [PinsterTeam/Frontend#9]
We'll probably end up deploying using circleci. We can use an s3 static website or if that is too much of a pain in the ass we can spin up an elasticbeanstalk or ec2 stack to run a node server to host the front end. 

S3 is preferable since it's cacheable in cloudfront easily, if we make a cloudfront distribution for the bucket.
The only caveats with s3 static websites is that the routing can get fucky since really only the `/` route "exists" so we'll have to fiddle with s3's redirecting stuff. More research is needed.

One sidenote with the s3 bucket is that in order for us to be able to use our static site with amazon's SSL certificate stuff is to name the actual bucket the same as what our end domain will be. So in this case, for dev we'll probably do `dev.pinster.io` and production's s3 bucket will be `prod.pinster.io`.(Because DNS is screwed up for `pinster.io` currently so we'll have to use our environment name for the moment). That way we can use amazon's SSL stuff so our site can be HTTPS

**Comment by stretch1414** [comment]
The create react app documentation has some steps for setting up an S3 static.  So probably go that route first.

**Comment by scytherswings** [comment]
Oh I forgot to mention serverless framework makes this deployment stuff pretty easy, we should be able to use that to create a static s3 website, though I'm not 100% sure you can use serverless framework without a lambda. Either way, we'll probably have to write some cloudformation anyway so we might just have to write that ourselves. Though I'd like to avoid writing it directly since that is literally torture.

**Comment by stretch1414** [comment]
https://medium.com/@omgwtfmarc/deploying-create-react-app-to-s3-or-cloudfront-48dae4ce0af

**Comment by scytherswings** [comment]
Ahh, that's a manual tutorial and is fine to get us up and running, but long-term I prefer to have infrastructure as code via cloudformation templates. It makes deploying things to test environments and unfucking a lot easier and safer.

**Comment by stretch1414** [comment]
Oh that's fine, I just figured it might be a good reference to get things started.

**Comment by stretch1414** [comment]
https://medium.com/all-technology-feeds/launching-a-static-site-with-react-aws-cloudfront-180f7a623675

**Comment by scytherswings** [comment]
I updated the description because of the message I left in the general chat about DNS for pinster.io being cached for like... 20 days.

**Comment by scytherswings** [comment]
Also this is a relevant article https://medium.com/@sbuckpesch/setup-aws-s3-static-website-hosting-using-ssl-acm-34d41d32e394

**Comment by stretch1414** [comment]
React should handle the routes for us, so that isn't an issue.  And I've seen that 2nd article.

**Comment by stretch1414** [comment]
So I thought we were going to use CloudFormation to generate the CloudFront to host the static website in S3.  Unless I am misunderstanding how this is supposed to work..

**Comment by stretch1414** [comment]
And makes sense for the bucket name, but can it have periods?
